-- 메뉴카드 질문 스텝 (상품별 JSON)
alter table public.products add column if not exists fortune_questions jsonb;

comment on column public.products.fortune_questions is '점사 질문 스텝 [{id,prompt,choices[]}]. 비어 있으면 기본 질문 세트 사용.';

update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"꿈에서 가장 선명하게 기억에 남는 장면이 무엇인가요?","choices":["① 누군가와 만나거나 재회하는 장면","② 쫓기거나 떨어지는 장면","③ 낯선 공간이나 길을 헤매는 장면","④ 물, 불, 하늘 같은 자연의 장면"]},{"id":"fq2","prompt":"꿈속에서 느꼈던 감정이 지금도 남아있나요?","choices":["① 네, 아직도 마음이 묘하게 울렁거려요","② 슬프거나 그리운 감정이 남아있어요","③ 불안하거나 찜찜한 기분이 있어요","④ 잘 모르겠어요, 그냥 신경 쓰여요"]},{"id":"fq3","prompt":"요즘 비슷한 꿈을 반복해서 꾸고 있나요?","choices":["① 네, 비슷한 꿈이 계속 나와요","② 어젯밤 꿈만 유독 이상했어요","③ 최근 들어 꿈이 부쩍 많아졌어요","④ 잘 모르겠지만 왠지 찜찜해요"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'dream-lastnight';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"2025년을 한 단어로 표현한다면?","choices":["① 버팀 — 힘들었지만 견뎌낸 한 해","② 전환 — 무언가 달라지기 시작한 해","③ 기다림 — 아직 원하는 게 이루어지지 않은 해","④ 혼란 — 뭘 해야 할지 몰랐던 한 해"]},{"id":"fq2","prompt":"올해 꼭 이루고 싶은 것이 있다면?","choices":["① 사랑 — 좋은 인연을 만나고 싶어요","② 돈 — 경제적으로 나아지고 싶어요","③ 일 — 커리어에서 변화가 생겼으면 해요","④ 안정 — 그냥 흔들리지 않았으면 해요"]},{"id":"fq3","prompt":"2026년에 가장 두려운 것은?","choices":["① 또 혼자일까봐","② 지금보다 더 나빠질까봐","③ 중요한 결정을 잘못 내릴까봐","④ 시간만 흘러가고 달라지는 게 없을까봐"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'tojeong-2026';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"그 사람 생각이 가장 많이 날 때가 언제인가요?","choices":["① 밤에 혼자 있을 때","② 예전에 같이 갔던 장소에 갈 때","③ 그 사람이 좋아하던 것을 볼 때","④ 특별한 이유 없이 불쑥 떠올라요"]},{"id":"fq2","prompt":"마지막으로 연락하거나 만난 게 얼마나 됐나요?","choices":["① 일주일도 안 됐어요","② 한 달 정도 됐어요","③ 몇 달이 지났어요","④ 1년 이상 됐어요"]},{"id":"fq3","prompt":"그 사람이 지금 나를 어떻게 생각하고 있을 것 같나요?","choices":["① 가끔은 생각하겠지만 연락은 안 할 것 같아요","② 나를 그리워하고 있을 것 같아요","③ 이미 잊었을 것 같아서 두려워요","④ 솔직히 전혀 모르겠어요"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'mind-now';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"2026년에 중요한 일정이 예정되어 있나요?","choices":["① 결혼 또는 이사 계획이 있어요","② 창업이나 개업을 준비 중이에요","③ 큰 계약이나 시험이 있어요","④ 아직 확정은 아니지만 계획 중이에요"]},{"id":"fq2","prompt":"날을 고를 때 가장 신경 쓰는 것은?","choices":["① 사주나 운세 상 좋은 날인지","② 가족이나 상대방 일정과 맞는지","③ 계절이나 날씨가 좋은지","④ 그냥 빨리 진행하고 싶어요"]},{"id":"fq3","prompt":"과거에 날을 잘못 골라 후회한 경험이 있나요?","choices":["① 네, 그 뒤로 꼭 날을 가려요","② 직접 경험은 없지만 주변에서 봤어요","③ 미신이라 생각했는데 요즘 마음이 바뀌었어요","④ 없지만 이번엔 제대로 알아보고 싶어요"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'calendar-2026';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"그 사람과 마지막으로 만났던 날이 기억나나요?","choices":["① 네, 그날이 아직도 선명해요","② 흐릿하지만 감정만은 남아있어요","③ 기억하고 싶지 않아서 지우려 했어요","④ 사실 제대로 된 이별도 못 했어요"]},{"id":"fq2","prompt":"다시 만나게 된다면 가장 먼저 하고 싶은 말은?","choices":["① 보고 싶었다고 솔직하게 말하고 싶어요","② 그동안 잘 지냈냐고 가볍게 시작하고 싶어요","③ 왜 그랬냐고 묻고 싶어요","④ 아무 말도 못 할 것 같아요"]},{"id":"fq3","prompt":"지금도 그 사람이 나를 기억하고 있을 것 같나요?","choices":["① 네, 그 사람도 잊지 못했을 것 같아요","② 아마 기억은 하겠지만 연락은 안 할 것 같아요","③ 솔직히 잊었을까봐 무서워요","④ 모르겠어요, 그래서 더 궁금해요"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'reunion-maybe';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"2026년 중 가장 기대되는 달이 있나요?","choices":["① 상반기 (1~6월) 중 뭔가 있을 것 같아요","② 하반기 (7~12월)에 변화가 있을 것 같아요","③ 특별히 기대되는 달보다는 전체 흐름이 궁금해요","④ 언제든 좋으니 좋은 일이 생겼으면 해요"]},{"id":"fq2","prompt":"올해 반드시 바꾸고 싶은 것이 있다면?","choices":["① 연애 혹은 결혼 상태","② 직장이나 수입","③ 주거나 생활 환경","④ 나 자신의 마음이나 습관"]},{"id":"fq3","prompt":"1년 후 이맘때, 어떤 모습이길 바라나요?","choices":["① 사랑하는 사람과 함께 있는 모습","② 경제적으로 한 단계 나아진 모습","③ 하고 싶은 일을 하고 있는 모습","④ 지금보다 마음이 평온한 모습"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'newyear-2026';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"아이가 태어난 날, 처음 안았을 때 어떤 감정이 들었나요?","choices":["① 말로 표현할 수 없는 벅참이 있었어요","② 두렵고 막막했지만 사랑스러웠어요","③ 아직 실감이 나지 않았어요","④ 이 아이를 지켜야 한다는 책임감이 먼저였어요"]},{"id":"fq2","prompt":"부모로서 아이에게 가장 물려주고 싶은 것은?","choices":["① 좋은 성격과 인간관계","② 경제적 안정과 기반","③ 하고 싶은 일을 할 수 있는 용기","④ 건강하고 행복한 삶"]},{"id":"fq3","prompt":"아이와 나, 가장 많이 닮았다고 느끼는 부분은?","choices":["① 표정이나 행동 같은 외적인 면","② 고집이나 감수성 같은 성격","③ 어떤 것에 집중하거나 빠져드는 방식","④ 아직 잘 모르겠어요, 아직 어려서요"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'child-saju';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"어떤 중요한 결정을 앞두고 계신가요?","choices":["① 결혼 날짜를 잡아야 해요","② 이사할 집을 구하고 있어요","③ 창업이나 개업을 준비 중이에요","④ 아직 확정은 아니지만 준비 중이에요"]},{"id":"fq2","prompt":"그 결정을 내리기까지 얼마나 고민하셨나요?","choices":["① 오래전부터 계획해온 일이에요","② 최근 들어 갑자기 결정한 편이에요","③ 아직도 확신이 서지 않아요","④ 마음은 정했는데 타이밍이 문제예요"]},{"id":"fq3","prompt":"이 결정, 주변 사람들은 어떻게 반응하나요?","choices":["① 대부분 응원해줘요","② 걱정하는 사람도 있어요","③ 아직 말하지 않았어요","④ 혼자 감당하고 있어요"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'taekil-goodday';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"요즘 일이 즐거운가요?","choices":["① 네, 보람은 있는데 뭔가 부족해요","② 아니요, 지치고 답답한 게 쌓이고 있어요","③ 그냥 버티고 있는 것 같아요","④ 변화가 필요한 시점이라는 건 알아요"]},{"id":"fq2","prompt":"지금 직장에서 가장 답답한 것은?","choices":["① 성장이 멈춘 것 같은 느낌","② 노력에 비해 인정받지 못하는 것","③ 사람 관계가 힘들어요","④ 연봉이나 대우가 기대에 못 미쳐요"]},{"id":"fq3","prompt":"5년 후 자신의 모습을 상상해본다면?","choices":["① 지금과 다른 일을 하고 있을 것 같아요","② 지금 하는 일에서 더 높은 위치에 있고 싶어요","③ 내 사업을 하고 있으면 좋겠어요","④ 솔직히 잘 그려지지 않아서 불안해요"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'career-timing';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"이상형을 한 문장으로 표현한다면?","choices":["① 나를 편안하게 해주는 사람","② 함께 성장할 수 있는 사람","③ 유머 있고 함께 있으면 즐거운 사람","④ 믿고 기댈 수 있는 든든한 사람"]},{"id":"fq2","prompt":"연애에서 가장 중요하게 생각하는 것은?","choices":["① 서로를 향한 감정의 크기","② 가치관과 생활방식이 맞는 것","③ 경제적 조건과 미래 안정성","④ 가족과 주변 환경이 맞는 것"]},{"id":"fq3","prompt":"지금 이 순간, 마음속에 떠오르는 사람이 있나요?","choices":["① 네, 특정한 사람이 있어요","② 막연하게 기다리고 있는 사람이에요","③ 있었는데 지금은 정리된 상태예요","④ 아직 만나지 못한 것 같아요"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'future-spouse';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"태어난 계절이 본인의 성격과 닮아있다고 느끼나요?","choices":["① 네, 꽤 맞는 것 같아요","② 반반인 것 같아요","③ 잘 모르겠지만 궁금해졌어요","④ 계절보다 사주가 더 정확한 것 같아요"]},{"id":"fq2","prompt":"지금 인생에서 가장 풀리지 않는 숙제는?","choices":["① 사람과의 관계","② 돈이나 일","③ 나 자신에 대한 이해","④ 미래에 대한 불안"]},{"id":"fq3","prompt":"사주를 보기 전, 가장 먼저 확인하고 싶은 것은?","choices":["① 올해의 전체적인 운의 흐름","② 사랑과 인연에 관한 것","③ 직업과 재물 운","④ 타고난 성격과 적성"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'saju-classic';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"두 사람이 처음 만나게 된 계기는?","choices":["① 지인 소개나 소셜을 통해 만났어요","② 일이나 학교에서 자연스럽게 가까워졌어요","③ 우연한 만남이었는데 운명처럼 느껴졌어요","④ 오래 알고 지냈는데 감정이 생겼어요"]},{"id":"fq2","prompt":"이 사람과 함께할 미래를 상상해본 적 있나요?","choices":["① 네, 자주 그려봐요","② 가끔 생각해보는데 확신이 없어요","③ 상상은 되는데 현실이 될지 모르겠어요","④ 아직 그 단계까지는 아닌 것 같아요"]},{"id":"fq3","prompt":"지금 이 관계에서 가장 확인하고 싶은 것은?","choices":["① 이 사람이 나를 얼마나 좋아하는지","② 우리가 잘 맞는 사람인지","③ 결혼까지 갈 수 있는 사이인지","④ 앞으로 어떤 방향으로 흘러갈지"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'compat-howfar';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"요즘 밤하늘을 올려다본 적 있나요?","choices":["① 네, 요즘 유독 하늘을 많이 봐요","② 바빠서 그럴 여유가 없었어요","③ 별을 보면서 생각이 많아지는 편이에요","④ 요즘 뭔가 달라진 것 같은 느낌이 있어요"]},{"id":"fq2","prompt":"인생에서 운명이라고 느꼈던 순간이 있었나요?","choices":["① 네, 분명히 있었어요","② 우연이라기엔 너무 이상한 일이 있었어요","③ 잘 모르겠지만 최근 그런 느낌이 있어요","④ 지금 바로 그 순간인 것 같아요"]},{"id":"fq3","prompt":"2026년, 어떤 흐름이 바뀌기를 기다리고 있나요?","choices":["① 사랑과 인연의 흐름","② 일과 돈의 흐름","③ 인간관계와 환경의 흐름","④ 내 마음과 방향의 흐름"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'zimi-2026-flow';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"돈과의 관계에서 가장 힘들었던 시기가 언제였나요?","choices":["① 사회초년생 때 아무것도 없었을 때","② 사업이나 투자에서 손해를 봤을 때","③ 지금이 가장 힘든 것 같아요","④ 벌기는 하는데 모이지 않는 지금"]},{"id":"fq2","prompt":"지금 재정 상태를 한 단어로 표현한다면?","choices":["① 빠듯함 — 매달 빠듯하게 살아가요","② 정체 — 늘지도 줄지도 않아요","③ 불안 — 앞으로가 걱정돼요","④ 기대 — 곧 나아질 것 같아요"]},{"id":"fq3","prompt":"부자가 된다면 가장 먼저 하고 싶은 일은?","choices":["① 가족과 부모님을 편하게 해드리고 싶어요","② 하고 싶었던 일이나 사업을 시작하고 싶어요","③ 집을 사거나 안정된 기반을 만들고 싶어요","④ 걱정 없이 좋아하는 것을 하며 살고 싶어요"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'wealth-graph';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"자신을 별에 비유한다면 어떤 별일 것 같나요?","choices":["① 밝게 빛나지만 혼자인 별","② 무리 속에서 함께 빛나는 별","③ 잘 보이지 않지만 꾸준히 빛나는 별","④ 아직 빛을 찾고 있는 별"]},{"id":"fq2","prompt":"태어난 날과 시간이 지금의 나를 만들었다고 느끼나요?","choices":["① 네, 많은 것이 설명이 돼요","② 반반인 것 같아요","③ 그런 것 같기도 하고 아닌 것 같기도 해요","④ 잘 몰랐는데 지금 궁금해졌어요"]},{"id":"fq3","prompt":"삶에서 가장 뚜렷하게 느끼는 자신의 특성은?","choices":["① 감수성이 풍부하고 감정이 깊어요","② 한 번 빠지면 끝까지 가는 편이에요","③ 혼자 있는 게 편하고 생각이 많아요","④ 사람들과 함께할 때 에너지가 생겨요"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'zimi-chart';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"아이의 이름에 어떤 의미를 담고 싶으신가요?","choices":["① 건강하고 오래 행복하길 바라는 마음","② 세상에서 빛나는 존재가 되길 바라는 마음","③ 좋은 사람들과 함께하길 바라는 마음","④ 하고 싶은 걸 하며 자유롭게 살길 바라는 마음"]},{"id":"fq2","prompt":"아이가 이름을 들었을 때 어떤 느낌이었으면 하나요?","choices":["① 부드럽고 따뜻한 느낌","② 강하고 단단한 느낌","③ 세련되고 기억에 남는 느낌","④ 친근하고 편안한 느낌"]},{"id":"fq3","prompt":"가족 중에 이름에 얽힌 이야기나 이어받고 싶은 글자가 있나요?","choices":["① 네, 이어받고 싶은 글자나 의미가 있어요","② 특별한 건 없지만 가족과 어울렸으면 해요","③ 완전히 새로운 이름을 짓고 싶어요","④ 아직 어떻게 할지 모르겠어요"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'naming-baby';
update public.products set fortune_questions = $yeonun_fortune_questions_json$[{"id":"fq1","prompt":"지금 자신의 인생이 어느 챕터에 있다고 느끼나요?","choices":["① 아직 시작도 안 한 것 같은 초반","② 한창 바쁘게 살아가는 중반","③ 뭔가 정리되고 안정되는 전환점","④ 지나온 것들을 돌아보게 되는 시기"]},{"id":"fq2","prompt":"과거의 나에게 한 마디 전할 수 있다면?","choices":["① 더 용기 있게 살라고 말해주고 싶어요","② 그 걱정들 별거 아니라고 말해주고 싶어요","③ 그때 그 선택이 맞았다고 말해주고 싶어요","④ 조금 더 나를 아끼라고 말해주고 싶어요"]},{"id":"fq3","prompt":"인생에서 아직 이루지 못한 꿈이 있다면?","choices":["① 사랑하는 사람과 함께하는 삶","② 내가 원하는 일을 하며 사는 것","③ 경제적 자유","④ 후회 없이 살았다는 느낌"]}]$yeonun_fortune_questions_json$::jsonb where fortune_questions is null and slug = 'lifetime-master';
